# Generated by Django 4.2.20 on 2025-06-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='defult_profile_picture.png', upload_to='profile_path'),
        ),
    ]
