# Generated by Django 4.2.20 on 2025-06-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bpdy',
            new_name='body',
        ),
    ]
