# Generated by Django 4.2.20 on 2025-07-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
